name: build and publish imgs workflow

on:
  workflow_call:
    inputs:
      build_type:
        required: true
        type: string

defaults:
  run:
    shell: bash

jobs:
  compute-matrix:
    runs-on: ubuntu-latest
    outputs:
      MATRIX: ${{ steps.compute-matrix.outputs.MATRIX }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Compute matrix
        id: compute-matrix
        run: |
          MATRIX=$(ci/compute-mx.sh)
          echo "MATRIX=${MATRIX}" | tee -a ${GITHUB_OUTPUT}
  docker:
    needs: compute-matrix
    strategy:
      matrix: ${{ fromJSON(needs.compute-matrix.outputs.MATRIX) }}
      fail-fast: false
    secrets: inherit
    uses: ./.github/workflows/build-image.yml
    with:
      ARCHES: ${{ toJSON(matrix.ARCHES) }}
      CUDA_VER: ${{ matrix.CUDA_VER }}
      LINUX_VER: ${{ matrix.LINUX_VER }}
      PYTHON_VER: ${{ matrix.PYTHON_VER }}
      IMAGE_REPO: ${{ matrix.IMAGE_REPO }}
      TAG: rapidsai/${{ matrix.IMAGE_REPO }}:cuda${{ matrix.CUDA_VER }}-base-${{ matrix.LINUX_VER }}-py${{ matrix.PYTHON_VER }}
      BUILD_TYPE: ${{ inputs.build_type }}
  build-multiarch-manifest:
    if: inputs.build_type == 'branch'
    needs: [docker, compute-matrix]
    strategy:
      matrix: ${{ fromJSON(needs.compute-matrix.outputs.MATRIX) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.GPUCIBOT_DOCKERHUB_USER }}
          password: ${{ secrets.GPUCIBOT_DOCKERHUB_TOKEN }}
      - name: Create multiarch manifest
        run: |
          LATEST_CUDA_VER=$(yq '.CUDA_VER | sort | .[-1]' axis.yaml)
          LATEST_PYTHON_VER=$(yq -o json '.PYTHON_VER' axis.yaml | jq -r 'max_by(split(".") | map(tonumber))')
          LATEST_UBUNTU_VER=$(yq '.LINUX_VER | map(select(. == "*ubuntu*")) | sort | .[-1]' axis.yaml)

          source_tags=()
          tag="rapidsai/${{ needs.compute-matrix.outputs.IMAGE_REPO }}:cuda${{ matrix.CUDA_VER }}-base-${{ matrix.LINUX_VER }}-py${{ matrix.PYTHON_VER }}"
          for arch in $(echo '${{ toJSON(matrix.ARCHES) }}' | jq .[] -r); do
            source_tags+=("${tag}-${arch}")
          done

          docker manifest create ${tag} ${source_tags[@]}
          docker manifest push ${tag}
          if [[
            "${LATEST_UBUNTU_VER}" == "${{ matrix.LINUX_VER }}" &&
            "${LATEST_CUDA_VER}" == "${{ matrix.CUDA_VER }}" &&
            "${LATEST_PYTHON_VER}" == "${{ matrix.PYTHON_VER }}"
          ]]; then
            docker manifest create rapidsai/${{ needs.compute-matrix.outputs.IMAGE_REPO }}:latest ${source_tags[@]}
            docker manifest push rapidsai/${{ needs.compute-matrix.outputs.IMAGE_REPO }}:latest
          fi
  delete-temp-images:
    if: inputs.build_type == 'branch'
    needs: [compute-matrix, build-multiarch-manifest]
    strategy:
      matrix: ${{ fromJSON(needs.compute-matrix.outputs.MATRIX) }}
    runs-on: ubuntu-latest
    steps:
      - name: Remove temporary images
        run: |
          HUB_TOKEN=$(
            curl -s -H "Content-Type: application/json" \
              -X POST \
              -d "{\"username\": \"${{ secrets.GPUCIBOT_DOCKERHUB_USER }}\", \"password\": \"${{ secrets.GPUCIBOT_DOCKERHUB_TOKEN }}\"}" \
              https://hub.docker.com/v2/users/login/ | jq -r .token \
          )

          org="rapidsai"
          repo="${{ needs.compute-matrix.outputs.IMAGE_REPO }}"
          tag="cuda${{ matrix.CUDA_VER }}-base-${{ matrix.LINUX_VER }}-py${{ matrix.PYTHON_VER }}"

          for arch in $(echo '${{ toJSON(matrix.ARCHES) }}' | jq .[] -r); do
            curl -i -X DELETE \
              -H "Accept: application/json" \
              -H "Authorization: JWT $HUB_TOKEN" \
              "https://hub.docker.com/v2/repositories/$org/$repo/tags/$tag-$arch/"
          done